# Generated by Django 5.0.4 on 2024-04-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('advertiser', 'Advertiser'), ('partners', 'Partners'), ('vendors', 'Vendors')], max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('legal_entity_name', models.CharField(max_length=100)),
                ('org_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('org_website', models.URLField(blank=True, null=True)),
                ('GSTIN', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
