# Generated by Django 5.0.4 on 2024-06-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fund_corpus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
