# Generated by Django 5.0.4 on 2024-07-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_fund_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('donor', 'Donor'), ('charity', 'Charity')], max_length=20),
        ),
    ]
