# Generated by Django 5.0.4 on 2024-04-25 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casepurpose',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
        migrations.AddField(
            model_name='casequery',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
