# Generated by Django 5.0.4 on 2024-05-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_rename_notes_caseevaluation_approver_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='disbursement_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='repay_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='repay_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='repayment_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CaseDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, default=0, verbose_name='[Created By User ID]')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, verbose_name='[Updated By User ID]')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('installment_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('planned_date', models.DateTimeField(auto_now=True, null=True)),
                ('disbursed_date', models.DateTimeField(auto_now=True, null=True)),
                ('disbursed_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tot_disbursed_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('disbursement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
            options={
                'db_table': 'case_disbursement',
            },
        ),
        migrations.CreateModel(
            name='CaseRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, default=0, verbose_name='[Created By User ID]')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, verbose_name='[Updated By User ID]')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('planned_repayment_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('planned_date', models.DateTimeField(auto_now=True, null=True)),
                ('repayment_date', models.DateTimeField(auto_now=True, null=True)),
                ('actual_repayment_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('repayment_txn_info', models.CharField(blank=True, max_length=50, null=True)),
                ('outstanding_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tot_repayed_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('repayment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
            options={
                'db_table': 'case_repayment',
            },
        ),
    ]
