# Generated by Django 5.0.4 on 2024-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_case_approved_amt_case_disbursement_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedisbursement',
            name='disbursement_txn_info',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='caserepayment',
            name='repayment_txn_info',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
