# Generated by Django 5.0.4 on 2024-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_casedisbursement_disbursement_txn_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedisbursement',
            name='disbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casedisbursement',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caserepayment',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caserepayment',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
