# Generated by Django 5.0.4 on 2024-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_alter_casedisbursement_disbursed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new', 'New'), ('verification', 'Verification'), ('evaluation', 'Evaluation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('undecided', 'Undecided'), ('disbursement', 'Disbursement'), ('repayment', 'Repayment'), ('other', 'Other')], max_length=50),
        ),
    ]
