# Generated by Django 5.0.4 on 2024-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_alter_case_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='repayment_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='total_disbursment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
