# Generated by Django 5.0.4 on 2024-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_case_repayment_received_case_total_disbursment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='repay_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
