# Generated by Django 5.0.4 on 2024-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_case_repay_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovseeddata',
            name='input_type',
            field=models.CharField(choices=[(' ', 'NULL'), ('lov', 'LOV'), ('radio_button', 'Radio Button'), ('checkbox', 'Checkbox'), ('textbox', 'Textarea'), ('inputbox', 'Inputbox'), ('file', 'File'), ('radio_button', 'Radio Button')], max_length=30),
        ),
    ]
