# Generated by Django 5.0.4 on 2024-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_alter_lovseeddata_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='purpose/')),
            ],
        ),
    ]
