# Generated by Django 5.0.4 on 2024-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purpose/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
