# Generated by Django 5.0.4 on 2024-06-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_fileupload_delete_imageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='total_disbursment',
            new_name='total_disbursement',
        ),
    ]
