# Generated by Django 5.0.4 on 2024-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_rename_total_disbursment_case_total_disbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovseeddata',
            name='input_type',
            field=models.CharField(choices=[(' ', 'NULL'), ('lov', 'LOV'), ('radio_button', 'Radio Button'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea'), ('inputbox', 'Inputbox'), ('file', 'File'), ('radio_button', 'Radio Button')], max_length=30),
        ),
    ]
