# Generated by Django 5.0.4 on 2024-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='b_phoneno',
            new_name='phoneno',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='b_profession',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='b_profile_pic',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='cur_town',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='period_of_stay',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
