# Generated by Django 5.0.4 on 2024-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_b_phoneno_customuser_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Married'), ('unmarried', 'Unmarried'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('other', 'Other')], max_length=30),
        ),
    ]
