# Generated by Django 5.0.4 on 2024-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Unmarried'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('other', 'Other')], max_length=30),
        ),
    ]
