# Generated by Django 5.0.4 on 2024-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_state_customuser_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user_id', 'address_type')},
        ),
    ]
