# Generated by Django 5.0.4 on 2024-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phoneno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
