# Generated by Django 5.0.4 on 2024-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
