# Generated by Django 5.0.4 on 2024-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_default_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_proof_copy',
            field=models.FileField(blank=True, null=True, upload_to='address_proof/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity_proof_copy',
            field=models.FileField(blank=True, null=True, upload_to='identity_proof/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='income_copy',
            field=models.FileField(blank=True, null=True, upload_to='income_proof/'),
        ),
    ]
