# Generated by Django 5.0.4 on 2024-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customuser_address_proof_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', 'Blank'), ('married', 'Married'), ('single', 'Unmarried'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
