# Generated by Django 5.0.4 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_customuser_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
